//Rival actions
export const RIVAL_FETCH_INIT = 'RIVAL: FETCH_INIT';
export const RIVAL_FETCH_SUCCESS = 'RIVAL: FETCH_SUCCESS';
export const RIVAL_FETCH_FAIL = 'RIVAL: FETCH_FAIL';

export const RIVAL_VOTE_INIT = 'RIVAL: VOTE_INIT';

//Leader actions
export const LEADERS_FETCH_INIT = 'LEADERS: FETCH_INIT';
export const LEADERS_FETCH_SUCCESS = 'LEADERS: FETCH_SUCCESS';
export const LEADERS_FETCH_FAIL = 'LEADERS: FETCH_FAIL';
